export const mockData = [
    {
        id: 1,
        title: "Introduction to JavaScript",
        author: "John Doe",
        authorEmail: "author@mail.com",
        description: "Learn the basics of JavaScript programming language.",
        tags: ["JavaScript", "Programming", "Web Development"],
        likeCount: 12,
        commentCount: 22,
        thumbnailid: "237/200/300",
        liveLink: "https://www.example.com",
        sourceLink: "https://www.example.com",
        promoted: false,
    },
    {
        id: 2,
        title: "Python for Beginners",
        author: "Jane Smith",
        authorEmail: "author@mail.com",
        description: "A beginner's guide to Python programming.",
        tags: ["Python", "Programming", "Beginners"],
        likeCount: 10,
        commentCount: 12,
        thumbnailid: "237/200/300",
        liveLink: "https://www.example.com",
        sourceLink: "https://www.example.com",
        promoted: false,
    },
    {
        id: 3,
        title: "Data Science with R",
        author: "Michael Johnson",
        authorEmail: "author@mail.com",
        description: "Explore data science concepts using the R language.",
        tags: ["R", "Data Science", "Programming"],
        likeCount: 1,
        commentCount: 2,
        thumbnailid: "237/200/300",
        liveLink: "https://www.example.com",
        sourceLink: "https://www.example.com",
        promoted: false,
    },
    {
        id: 4,
        title: "HTML and CSS Basics",
        author: "Emily Adams",
        authorEmail: "author@mail.com",
        description: "Learn the fundamentals of HTML and CSS for web development.",
        tags: ["HTML", "CSS", "Web Development"],
        likeCount: 12,
        commentCount: 32,
        thumbnailid: "237/200/300",
        liveLink: "https://www.example.com",
        sourceLink: "https://www.example.com",
        promoted: false,
    },
    {
        id: 5,
        title: "Java Programming",
        author: "David Lee",
        authorEmail: "author@mail.com",
        description: "An introduction to Java programming language.",
        tags: ["Java", "Programming", "OOP"],
        likeCount: 2,
        commentCount: 12,
        thumbnailid: "237/200/300",
        liveLink: "https://www.example.com",
        sourceLink: "https://www.example.com",
        promoted: false,
    }
]

export const TAGS = ["All", "Web Development", "Python", "MERN", "JavaScript", "Tailwind", "HTML", "CSS", "Android", "Programming", "Node Js", "Express", "MongoDB", "Mongoose"]